@echo off
cd backend
if not exist venv (
    echo Creating virtual environment...
    py -m venv venv
)
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Flask server...
py app.py
