"""Allow null question_id in messages table

Revision ID: 3b3070edb1fe
Revises: 
Create Date: 2026-01-21 10:54:33.239051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3070edb1fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('ix_message_recipients_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_recipients_recipient_id'))
        batch_op.drop_constraint(batch_op.f('unique_message_recipient'), type_='unique')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('unique_message_recipient'), ['message_id', 'recipient_id'])
        batch_op.create_index(batch_op.f('ix_message_recipients_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_recipients_message_id'), ['message_id'], unique=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
